### ISSUE TITLE
Implement integration pipeline

### ISSUE THREAD

**Issue by RobinTTY** [RobinTTY/PersonalFinanceDashboard#11]
I want to automate build, test and publish steps of my application.
I should therefore implement an integration pipeline which takes care of that.
Github actions should be appropriate.

## Tasks

- [ ] Add build step
  - [ ] Build application
    - [x] Build server
    - [ ] Build client
  - [x] Build docs (#25)
- [ ] Add testing step
- [ ] Add deploy step (packaging of application)
  - [x] Deploy docs (#25)
  - [ ] Package application
