### ISSUE TITLE
Investigate interfacing with banking APIs

### ISSUE THREAD

**Issue by RobinTTY** [RobinTTY/PersonalFinanceDashboard#2]
I want to be able to automatically pull in new bank transactions.
I should therefore investigate possible interfacing options with banking APIs.

## Notes

A third party provider is necessary since direct interfacing with PSD2 APIs requires licensing, which is very much non trivial.
There are at least some solutions to interface with banking APIs (PSD2) through third parties.

## Possibilities

- [x] [Nordigen](https://nordigen.com/en/) - Free option available
- [x] [Plaid](https://plaid.com/) - Free option available
- [x] [Truelayer](https://truelayer.com/) - Only paid?
- [x] [Tink](https://tink.com/) - Only paid?
- [x] [Saltedge](https://www.saltedge.com/products/account_information/coverage) - Free option available
