### ISSUE TITLE
Investigate possible design systems / UI component libraries

### ISSUE THREAD

**Issue by RobinTTY** [RobinTTY/PersonalFinanceDashboard#4]
I want to offer an excellent user experience, therefore my application should look modern and well rounded.
I should therefore employ an existing design system or UI component library to avoid implementing basic stuff myself and to have a coherent look and feel.

## Look at possible Solutions

- [x] [MUI](https://mui.com/) (Not associated with Google, only following Material-UI guidelines)
- [x] [atomize](https://atomizecode.com/)
- [x] [chakra](https://chakra-ui.com/)
- [x] [Bolt](https://boltdesignsystem.com/)
