### ISSUE TITLE
Implement bank account data import

### ISSUE THREAD

**Issue by RobinTTY** [RobinTTY/PersonalFinanceDashboard#55]
A user should be able to automatically retrieve balances and transaction data from their bank account by connecting them to the application. I already implemented the necessary client library to retrieve this data in #29.

Necessary work on the backend:

- [x] Implement necessary logic to connect and query bank accounts
- [x] Expose bank account data service via API

Necessary UI components for the client:

- [x] Implement institution search and selection (which bank should be connected to?)
- [x] Handle redirection upon completion of authentication with bank via GoCardless (information retrieval should be triggered)
- [x] Implement account selection from bank (one bank connection can hold many accounts)

Example how the institution selection can look like: [Nordigen UI](https://github.com/nordigen/nordigen-bank-ui)
